### ISSUE TITLE
[Dataset Create/Edit Form] Form field display issues

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/ckanext-datawagovautheme#18]
https://uat.landgate.links.com.au/dataset/new

Two issues here:

1. The field label, the field itself, and its help text are stacked vertically, not horizontally.
2. `<input type="text">` fields are defaulting to 172px wide, rather than filling up the available space as was the case previously.

UAT
![screen shot 2019-01-24 at 08 17 53](https://user-images.githubusercontent.com/5944358/51645743-94a42000-1fb0-11e9-8052-7ecf739d2fcf.png)

PROD
![screen shot 2019-01-24 at 08 17 39](https://user-images.githubusercontent.com/5944358/51645742-94a42000-1fb0-11e9-9415-56b4d6b0963c.png)

**Comment by krupalip** [comment]
Answers:
Two Issues
1. yes, fields are displayed vertically in the base ckan.
2. Couldn't reproduce the issue as I can see full width of inputbox.

Attaching screens for ref:
Create dataset form in base ckan
![create dataset- base ckan](https://user-images.githubusercontent.com/40553698/52547922-b7826100-2e05-11e9-9251-3cc931d7a050.png)

Create dataset form with datawagovautheme
![create dataset- datawagovautheme](https://user-images.githubusercontent.com/40553698/52548029-22339c80-2e06-11e9-8361-c6dc61092929.png)

**Comment by keithamoss** [comment]
@krupalip Well that's odd.

Could you have a look at the CSS being applied to the `<input>` elements on the create dataset form within your datawagovautheme'd CKAN please?

```html
<input id="field-author" type="text" name="author" value="" placeholder="Joe Bloggs">
```

On our UAT we have these rules applied (none of which are setting anything like `width: 100%;`):

```css
label, input, button, select, textarea {
    font-size: 16px;
}
input, button, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
input {
    line-height: normal;
}
button, input, optgroup, select, textarea {
    color: inherit;
    font: inherit;
    margin: 0;
}
* {
    -webkit-hyphens: none;
}
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
user agent stylesheet
input {
    -webkit-appearance: textfield;
    background-color: white;
    -webkit-rtl-ordering: logical;
    cursor: text;
    padding: 1px;
    border-width: 2px;
    border-style: inset;
    border-color: initial;
    border-image: initial;
}
user agent stylesheet
input, textarea, select, button {
    text-rendering: auto;
    color: initial;
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0px;
    text-shadow: none;
    display: inline-block;
    text-align: start;
    margin: 0em;
    font: 400 11px system-ui;
}
user agent stylesheet
input, textarea, select, button, meter, progress {
    -webkit-writing-mode: horizontal-tb !important;
}
body {
    background: #eff1f2;
    font-family: Arial, sans-serif;
    font-size: 16px;
    color: #565656;
    line-height: 1.59375em;
}
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #333333;
    background-color: #ffffff;
}
html {
    font-size: 10px;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
*:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
*:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```
